### ISSUE TITLE
First Issue, Timing

### ISSUE THREAD

**Issue by noelcopter** [vnamiran/UCIsd_NMV#1]
Guys lets set a day of week to work together just put the date and time you guys are free.
Me:
Monday after 12
Tuesday 2 - 5
Wednesday after 12
Thursday not free
Friday FORGET ABOUT IT

Free on weekends from now on ... yaaaay

hmm.. we can edit an issue... wonder if this is going to show on slack :8ball:

**Comment by vnamiran** [comment]
hi :)

**Comment by mewashin** [comment]
What's up. Does it work for me too?
